<?php
/*****************************************************************************
Copyright 2008 York University

Licensed under the Educational Community License (ECL), Version 2.0 or the New
BSD license. You may not use this file except in compliance with one these
Licenses.

You may obtain a copy of the ECL 2.0 License and BSD License at
https://source.fluidproject.org/svn/LICENSE.txt
*******************************************************************************/
?>
<?php
/* $Id: foot.inc,v 1.5 2005/04/14 17:51:13 greggmc Exp $ */

/* vim: set tabstop=4 shiftwidth=4 expandtab: */
?>
        </form>
        </div>
  </div> <!-- end body div -->
  
  <div class="clear"></div>
  <div id="footer">
  Powered By <?php echo($SITE['title']); ?>
  </div> <!-- end footer div -->
<br/>
</div> <!-- end main div -->
